// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _114032_Báez_Nicolás_Final_Prog_III.Models;

#nullable disable

namespace _114032_Báez_Nicolás_Final_Prog_III.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20240805183817_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_114032_Báez_Nicolás_Final_Prog_III.Models.Configuraciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ce1f7f6-5d4a-4ac5-a686-7b01c00e89eb"),
                            Nombre = "padding-top",
                            Valor = "50px"
                        },
                        new
                        {
                            Id = new Guid("548a0e70-844a-4132-9543-fc629c94b376"),
                            Nombre = "padding-left",
                            Valor = "100px"
                        });
                });

            modelBuilder.Entity("_114032_Báez_Nicolás_Final_Prog_III.Models.Provincias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16e03d16-f860-4127-9d86-0916a05e8852"),
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("77da6664-5e45-4137-9882-68c43d5db660"),
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("699357cc-1974-4970-8f7b-a85bb01b8fad"),
                            Nombre = "Salta"
                        });
                });

            modelBuilder.Entity("_114032_Báez_Nicolás_Final_Prog_III.Models.Sucursales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProvinciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TipoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("_114032_Báez_Nicolás_Final_Prog_III.Models.Tipos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c7a829f-269f-4132-8a9c-a747a6a2ca6a"),
                            Nombre = "Pequeña"
                        },
                        new
                        {
                            Id = new Guid("cb13987f-739e-4164-9820-f04820e46c72"),
                            Nombre = "Grande"
                        });
                });

            modelBuilder.Entity("_114032_Báez_Nicolás_Final_Prog_III.Models.Sucursales", b =>
                {
                    b.HasOne("_114032_Báez_Nicolás_Final_Prog_III.Models.Provincias", "IdProvinciaNavegation")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_114032_Báez_Nicolás_Final_Prog_III.Models.Tipos", "IdTipoNavegation")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProvinciaNavegation");

                    b.Navigation("IdTipoNavegation");
                });
#pragma warning restore 612, 618
        }
    }
}
